apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: gimbarr1717/yaroslav-repos:$PRODUCT_SERVICE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          volumeMounts:
          - name: config
            mountPath: /app/application.properties
            subPath: application.properties
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: petclinic-configmap
